export const COLLECTIONS = {
  USERS: "users",
  OTP_VERIFICATION: "otp_verification",
  PARENTS: "parents",
  PARENT_ADDRESSES: "parent_addresses",
  DRIVERS: "drivers",
  DRIVER_ADDRESSES: "driver_addresses",
  DRIVER_DOCUMENTS: "driver_documents",
  PINGS: "pings",
  ROLES: "roles",
  PASSWORD_RESETS: "password_resets",
  STUDENTS: "students",
  SCHOOLS: "schools",
  TRIPS: "trips",
  NOTIFICATIONS: "notifications",
  DRIVER_STUDENT_ASSIGNMENTS: "driver_student_assignments",
};

export const USERS_COLLECTION = COLLECTIONS.USERS;
export const OTP_VERIFICATION_COLLECTION = COLLECTIONS.OTP_VERIFICATION;
export const PARENTS_COLLECTION = COLLECTIONS.PARENTS;
export const PARENT_ADDRESSES_COLLECTION = COLLECTIONS.PARENT_ADDRESSES;
export const DRIVERS_COLLECTION = COLLECTIONS.DRIVERS;
export const DRIVER_ADDRESSES_COLLECTION = COLLECTIONS.DRIVER_ADDRESSES;
export const DRIVER_DOCUMENTS_COLLECTION = COLLECTIONS.DRIVER_DOCUMENTS;
export const PINGS_COLLECTION = COLLECTIONS.PINGS;
export const ROLES_COLLECTION = COLLECTIONS.ROLES;
export const STUDENTS_COLLECTION = COLLECTIONS.STUDENTS;
export const SCHOOLS_COLLECTION = COLLECTIONS.SCHOOLS;
export const TRIPS_COLLECTION = COLLECTIONS.TRIPS;
export const NOTIFICATIONS_COLLECTION = COLLECTIONS.NOTIFICATIONS;
export const DRIVER_STUDENT_ASSIGNMENTS_COLLECTION =
  COLLECTIONS.DRIVER_STUDENT_ASSIGNMENTS;
