export const COLLECTIONS = {
  USERS: "users",
  PARENTS: "parents",
  PARENT_ADDRESSES: "parent_addresses",
  DRIVERS: "drivers",
  DRIVER_ADDRESSES: "driver_addresses",
  DRIVER_DOCUMENTS: "driver_documents",
  SCHOOLS: "schools",
  STUDENTS: "students",
  DRIVER_STUDENT_ASSIGNMENTS: "driver_student_assignments",
  TRIPS: "trips",
  TRIP_STUDENTS: "trip_students",
  LOCATION_TRACKING: "location_tracking",
  DAILY_QR_OTP: "daily_qr_otp",
  NOTIFICATIONS: "notifications",
  DEVICE_TOKENS: "device_tokens",
  NOTIFICATION_PREFERENCES: "notification_preferences",
  SUBSCRIPTION_PLANS: "subscription_plans",
  PARENT_SUBSCRIPTIONS: "parent_subscriptions",
  SCHOOL_SUBSCRIPTIONS: "school_subscriptions",
  SCHOOL_STUDENT_CODES: "school_student_codes",
  PAYMENTS: "payments",
  RATINGS_REVIEWS: "ratings_reviews",
  SUPPORT_TICKETS: "support_tickets",
  AUDIT_LOGS: "audit_logs",
  ADMIN_PORTAL: "admin_portal",
  ADS: "ads",
  AD_INTERACTIONS: "ad_interactions",
  SCHOOL_EVENTS: "school_events",
  EVENT_RSVP: "event_rsvp",
  SCHOOL_PARENT_COMMUNITY: "school_parent_community",
  PARENT_CONNECTIONS: "parent_connections",
  COMMUNITY_POSTS: "community_posts",
  COMMUNITY_POST_REACTIONS: "community_post_reactions",
  COMMUNITY_POST_COMMENTS: "community_post_comments",
  ROLES: "roles",
  USER_ROLES: "user_roles",
  OTP_VERIFICATION: "otp_verification",
  DRIVER_ONBOARDING: "driver_onboarding",
  PINGS: "pings",
  PASSWORD_RESETS: "password_resets",
  SCHOOL_ADMINS: "school_admins",
};

export const USERS_COLLECTION = COLLECTIONS.USERS;
export const PARENTS_COLLECTION = COLLECTIONS.PARENTS;
export const PARENT_ADDRESSES_COLLECTION = COLLECTIONS.PARENT_ADDRESSES;
export const DRIVERS_COLLECTION = COLLECTIONS.DRIVERS;
export const DRIVER_ADDRESSES_COLLECTION = COLLECTIONS.DRIVER_ADDRESSES;
export const DRIVER_DOCUMENTS_COLLECTION = COLLECTIONS.DRIVER_DOCUMENTS;
export const SCHOOLS_COLLECTION = COLLECTIONS.SCHOOLS;
export const STUDENTS_COLLECTION = COLLECTIONS.STUDENTS;
export const DRIVER_STUDENT_ASSIGNMENTS_COLLECTION =
  COLLECTIONS.DRIVER_STUDENT_ASSIGNMENTS;
export const TRIPS_COLLECTION = COLLECTIONS.TRIPS;
export const TRIP_STUDENTS_COLLECTION = COLLECTIONS.TRIP_STUDENTS;
export const LOCATION_TRACKING_COLLECTION = COLLECTIONS.LOCATION_TRACKING;
export const DAILY_QR_OTP_COLLECTION = COLLECTIONS.DAILY_QR_OTP;
export const NOTIFICATIONS_COLLECTION = COLLECTIONS.NOTIFICATIONS;
export const DEVICE_TOKENS_COLLECTION = COLLECTIONS.DEVICE_TOKENS;
export const NOTIFICATION_PREFERENCES_COLLECTION =
  COLLECTIONS.NOTIFICATION_PREFERENCES;
export const SUBSCRIPTION_PLANS_COLLECTION = COLLECTIONS.SUBSCRIPTION_PLANS;
export const PARENT_SUBSCRIPTIONS_COLLECTION = COLLECTIONS.PARENT_SUBSCRIPTIONS;
export const SCHOOL_SUBSCRIPTIONS_COLLECTION = COLLECTIONS.SCHOOL_SUBSCRIPTIONS;
export const SCHOOL_STUDENT_CODES_COLLECTION = COLLECTIONS.SCHOOL_STUDENT_CODES;
export const PAYMENTS_COLLECTION = COLLECTIONS.PAYMENTS;
export const RATINGS_REVIEWS_COLLECTION = COLLECTIONS.RATINGS_REVIEWS;
export const SUPPORT_TICKETS_COLLECTION = COLLECTIONS.SUPPORT_TICKETS;
export const AUDIT_LOGS_COLLECTION = COLLECTIONS.AUDIT_LOGS;
export const ADMIN_PORTAL_COLLECTION = COLLECTIONS.ADMIN_PORTAL;
export const ADS_COLLECTION = COLLECTIONS.ADS;
export const AD_INTERACTIONS_COLLECTION = COLLECTIONS.AD_INTERACTIONS;
export const SCHOOL_EVENTS_COLLECTION = COLLECTIONS.SCHOOL_EVENTS;
export const EVENT_RSVP_COLLECTION = COLLECTIONS.EVENT_RSVP;
export const SCHOOL_PARENT_COMMUNITY_COLLECTION =
  COLLECTIONS.SCHOOL_PARENT_COMMUNITY;
export const PARENT_CONNECTIONS_COLLECTION = COLLECTIONS.PARENT_CONNECTIONS;
export const COMMUNITY_POSTS_COLLECTION = COLLECTIONS.COMMUNITY_POSTS;
export const COMMUNITY_POST_REACTIONS_COLLECTION =
  COLLECTIONS.COMMUNITY_POST_REACTIONS;
export const COMMUNITY_POST_COMMENTS_COLLECTION =
  COLLECTIONS.COMMUNITY_POST_COMMENTS;
export const ROLES_COLLECTION = COLLECTIONS.ROLES;
export const USER_ROLES_COLLECTION = COLLECTIONS.USER_ROLES;
export const OTP_VERIFICATION_COLLECTION = COLLECTIONS.OTP_VERIFICATION;
export const DRIVER_ONBOARDING_COLLECTION = COLLECTIONS.DRIVER_ONBOARDING;
export const PINGS_COLLECTION = COLLECTIONS.PINGS;
export const PASSWORD_RESETS_COLLECTION = COLLECTIONS.PASSWORD_RESETS;
export const SCHOOL_ADMINS_COLLECTION = COLLECTIONS.SCHOOL_ADMINS;
