export const COLLECTIONS = {
  USERS: "users",
  OTP_VERIFICATION: "otp_verification",
  PARENTS: "parents",
  PARENT_ADDRESSES: "parent_addresses",
  DRIVERS: "drivers",
  DRIVER_ONBOARDING: "driver_onboarding",
  DRIVER_ADDRESSES: "driver_addresses",
  DRIVER_DOCUMENTS: "driver_documents",
  PINGS: "pings",
  ROLES: "roles",
  PASSWORD_RESETS: "password_resets",
  STUDENTS: "students",
  SCHOOLS: "schools",
  TRIPS: "trips",
  TRIP_STUDENTS: "trip_students",
  NOTIFICATIONS: "notifications",
  DRIVER_STUDENT_ASSIGNMENTS: "driver_student_assignments",
  DAILY_QR_OTP: "daily_qr_otp",
  LOCATION_TRACKING: "location_tracking",
  SUBSCRIPTION_PLANS: "subscription_plans",
  PARENT_SUBSCRIPTIONS: "parent_subscriptions",
  PAYMENTS: "payments",
  RATINGS_REVIEWS: "ratings_reviews",
  ADMIN_PORTAL: "admin_portal",
  AUDIT_LOGS: "audit_logs",
};

export const USERS_COLLECTION = COLLECTIONS.USERS;
export const OTP_VERIFICATION_COLLECTION = COLLECTIONS.OTP_VERIFICATION;
export const PARENTS_COLLECTION = COLLECTIONS.PARENTS;
export const PARENT_ADDRESSES_COLLECTION = COLLECTIONS.PARENT_ADDRESSES;
export const DRIVERS_COLLECTION = COLLECTIONS.DRIVERS;
export const DRIVER_ADDRESSES_COLLECTION = COLLECTIONS.DRIVER_ADDRESSES;
export const DRIVER_DOCUMENTS_COLLECTION = COLLECTIONS.DRIVER_DOCUMENTS;
export const PINGS_COLLECTION = COLLECTIONS.PINGS;
export const ROLES_COLLECTION = COLLECTIONS.ROLES;
export const STUDENTS_COLLECTION = COLLECTIONS.STUDENTS;
export const SCHOOLS_COLLECTION = COLLECTIONS.SCHOOLS;
export const TRIPS_COLLECTION = COLLECTIONS.TRIPS;
export const TRIP_STUDENTS_COLLECTION = COLLECTIONS.TRIP_STUDENTS;
export const NOTIFICATIONS_COLLECTION = COLLECTIONS.NOTIFICATIONS;
export const DRIVER_STUDENT_ASSIGNMENTS_COLLECTION =
  COLLECTIONS.DRIVER_STUDENT_ASSIGNMENTS;
export const DAILY_QR_OTP_COLLECTION = COLLECTIONS.DAILY_QR_OTP;
export const LOCATION_TRACKING_COLLECTION = COLLECTIONS.LOCATION_TRACKING;
export const SUBSCRIPTION_PLANS_COLLECTION = COLLECTIONS.SUBSCRIPTION_PLANS;
export const PARENT_SUBSCRIPTIONS_COLLECTION = COLLECTIONS.PARENT_SUBSCRIPTIONS;
export const PAYMENTS_COLLECTION = COLLECTIONS.PAYMENTS;
export const RATINGS_REVIEWS_COLLECTION = COLLECTIONS.RATINGS_REVIEWS;
export const ADMIN_PORTAL_COLLECTION = COLLECTIONS.ADMIN_PORTAL;
export const AUDIT_LOGS_COLLECTION = COLLECTIONS.AUDIT_LOGS;
export const DRIVER_ONBOARDING_COLLECTION = COLLECTIONS.DRIVER_ONBOARDING;
