export const COLLECTIONS = {
  USERS: "users",
  OTP_VERIFICATION: "otp_verification",
  PINGS: "pings",
  ROLES: "roles",
  PASSWORD_RESETS: "password_resets",
  STUDENTS: "students",
  TRIPS: "trips",
  NOTIFICATIONS: "notifications",
  ADDRESSES: "addresses",
};

export const USERS_COLLECTION = COLLECTIONS.USERS;
export const OTP_VERIFICATION_COLLECTION = COLLECTIONS.OTP_VERIFICATION;
export const PINGS_COLLECTION = COLLECTIONS.PINGS;
export const STUDENTS_COLLECTION = COLLECTIONS.STUDENTS;
export const TRIPS_COLLECTION = COLLECTIONS.TRIPS;
export const NOTIFICATIONS_COLLECTION = COLLECTIONS.NOTIFICATIONS;
export const ADDRESSES_COLLECTION = COLLECTIONS.ADDRESSES;
